# Generated by Django 6.0.1 on 2026-01-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumeversion",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="resumeversion",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
