# Generated by Django 6.0.1 on 2026-01-15 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0004_resumeversion_cloudinary_public_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("cover_letter", "Cover Letter"),
                            ("job_match", "Job Match Analysis"),
                            ("interview_questions", "Interview Questions"),
                        ],
                        max_length=30,
                    ),
                ),
                ("input_job_description", models.TextField(blank=True)),
                ("input_resume_text", models.TextField(blank=True)),
                ("input_company_name", models.CharField(blank=True, max_length=255)),
                ("input_job_title", models.CharField(blank=True, max_length=255)),
                ("input_params", models.JSONField(blank=True, default=dict)),
                ("output_content", models.TextField()),
                ("output_metadata", models.JSONField(blank=True, default=dict)),
                ("model_used", models.CharField(max_length=100)),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("rating", models.IntegerField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_contents",
                        to="applications.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Content",
                "verbose_name_plural": "Generated Contents",
                "ordering": ["-created_at"],
            },
        ),
    ]
