# Generated by Django 6.0.1 on 2026-01-15 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screen'), ('technical', 'Technical'), ('behavioral', 'Behavioral'), ('coding', 'Coding Challenge'), ('system_design', 'System Design'), ('onsite', 'On-site'), ('hr', 'HR/Final'), ('other', 'Other')], default='phone', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('meeting_link', models.URLField(blank=True)),
                ('meeting_location', models.CharField(blank=True, max_length=255)),
                ('interviewer_names', models.CharField(blank=True, max_length=500)),
                ('interviewer_titles', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('preparation_notes', models.TextField(blank=True)),
                ('post_interview_notes', models.TextField(blank=True)),
                ('questions_asked', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
